{
  "models": [
    {
      "title": "Qwen 14B Coding",
      "provider": "ollama",
      "model": "qwen14b:latest"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Qwen 14B Autocomplete",
    "provider": "ollama",
    "model": "qwen14b:latest"
  }
}